apiVersion: v1
kind: Service
metadata:
  name: {{ template "demo.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "demo.name" . }}
    chart: {{ template "demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.app.port }}
      name: {{ template "demo.name" . }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
  selector:
    app: {{ template "demo.name" . }}
    release: {{ .Release.Name }}
