apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: sfilatov/myapp:v0.0.1
        imagePullPolicy: Always
        env:
        - name: HTTP_PORT
          value: "8082"
        ports:
        - containerPort: 8082
