name: test-release

on:
  push:
    branches: 
      - master
env:
  KUBU_CONFIG: ${{ secrets.K8s }}
jobs:
#  poll:
#    name: pool repo
#    runs-on: self-hosted
#    steps
  build:
    name: test-release
    runs-on: self-hosted
    steps:
      - name: pull repo
        run: git clone https://github.com/Shaverdoff/k8s-conf-demo.git
      - name: get pod
        run: kubectl get pod -A
      - name: where were are
        run: pwd && ls -lsa 
      - name: deply 
        run: kubectl apply -f k8s-conf-demo/manifests/deployment.yaml
