name: test-release

on:
  push:
    branches: 
      - master
env:
  KUBU_CONFIG: ${{ secrets.K8s }}
jobs:
  build:
    name: test-release
    runs-on: bitnami/kubectl:latest
    steps:
      - name: install keystone
        run: curl -sSL https://hub.mcs.mail.ru/repository/client-keystone-auth/latest/linux/client-install.sh | bash
      - name: get pod
        run: kubectl get pod -A
